name: Draw Map
on:
  push:
    branches:
      - main
      
jobs:
  add-missing:
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Download world
      run: |
        mkdir world2
        baseUrl="http://shifttech.xyz:8081/shifttechterraria/hourly/"
        curl -s "$baseUrl" | awk -F '"' '/href=/{print "'"$baseUrl"'"$2}' | xargs -I {} wget -nd -v -P world2/ {}
        
    - name: Commit and push
      run: |
        git config user.name "InfinityNichto"
        git config user.email "u5170201@gmail.com"
        git add .
        git commit -m "Filling file gaps"
        git push
