name: Draw Map

on:
  push:
    branches:
      - main
      
  schedule:
    - cron: "0 * * * *"
    
jobs:
  generate-map:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        max-parallel: [4]

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Download world
      run: |
        git add images
        currentTime=$(TZ=UTC+4 date +"%Y-%m-%d_%H")
        formattedTime=$(TZ="UTC+4" date +"%Y-%m-%d %H")
        formattedTime=$(date -d "${formattedTime}" +"%a, %b %Y -%l %p")
        target="http://shifttech.xyz:8081/shifttechterraria/hourly/"$(curl -s "http://shifttech.xyz:8081/shifttechterraria/hourly/" | awk -F '"' '/href=/{print $2}' | tail -n 1)
        wget -nd -v -P images -O "$formattedTime.wld" $target
        git commit -m "Add downloaded world file"
        git push
        
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-dev python3-setuptools libjpeg-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev
        python3 -m pip install --upgrade flyingsnake

    - name: Run flyingsnake
      run: |
        currentTime=$(TZ=UTC+4 date +"%Y-%m-%d_%H")
        formattedTime=$(TZ="UTC+4" date +"%Y-%m-%d %H")
        formattedTime=$(date -d "${formattedTime}" +"%a, %b %Y -%l %p")
        flyingsnake --no-wires "/images/$formattedTime.wld" "/images/$formattedTime.png"
        rm /images/$formattedTime.wld

    - name: Commit and push changes
      run: |
        git config user.name "GitHub Actions"
        git config user.email "actions@github.com"
        git add worlds
        git commit -m "Hourly world map update"
        git push
