name: Draw Map
on:
  schedule:
    - cron: "5 * * * *"
    
jobs:
  generate-map:
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Download world
      run: |
        target="http://shifttech.xyz:8081/shifttechterraria/hourly/"$(curl -s "http://shifttech.xyz:8081/shifttechterraria/hourly/" | awk -F '"' '/href=/{print $2}' | tail -n 1)
        wget -nd -v -O "images/temp.wld" $target
        # git add .
        # git commit -m "Add downloaded world file"
        # git push
        
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-dev python3-setuptools libjpeg-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev
        python3 -m pip install --upgrade flyingsnake

    - name: Run flyingsnake
      run: |
        formattedTime=$(TZ="UTC+4" date +"%a-%b-%Y-%H:00")
        formattedTime="${formattedTime}.png"
        target="$(curl -s "http://shifttech.xyz:8081/shifttechterraria/hourly/" | awk -F '"' '/href=.*\.wld/{latest=$2} END{print latest}' | sed 's/\.wld$/.png/')"
        flyingsnake --no-wires "images/temp.wld" "images/temp.png"
        mv images/temp.png "images/$formattedTime"
        
    - name: Commit and push
      run: |
        git config user.name "InfinityNichto"
        git config user.email "u5170201@gmail.com"
        rm images/temp.wld
        git add .
        git commit -m "Hourly world map update"
        git push
