name: Draw Map
on: 
  schedule:
    - cron: "0 * * * *"
    
jobs:
  generate-map:
    runs-on: ubuntu-latest
   
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Config user
      run: |
        git config user.name "InfinityNichto"
        git config user.email "u5170201@gmail.com"
    
    - name: Download world
      run: |
        mkdir images
        currentTime=$(TZ=UTC+4 date +"%Y-%m-%d_%H")
        target="http://shifttech.xyz:8081/shifttechterraria/hourly/"$(curl -s "http://shifttech.xyz:8081/shifttechterraria/hourly/" | awk -F '"' '/href=/{print $2}' | tail -n 1)
        wget -nd -v -O "images/temp.wld" $target
        # git add .
        # git commit -m "Add downloaded world file"
        # git push
        
    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y python3-pip python3-dev python3-setuptools libjpeg-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev
        python3 -m pip install --upgrade flyingsnake

    - name: Run flyingsnake
      run:
        currentTime=$(TZ=UTC+4 date +"%Y-%m-%d %H")
        formattedTime=$(TZ="UTC+4" date +"%Y-%m-%d %H")
        formattedTime=$(date -d "${formattedTime}"+"%a-%b-%Yz %l-%p").png
        flyingsnake --no-wires "images/temp.wld" "images/$formattedTime"

    - name: Commit and push
      run: |
        rm images/temp.wld
        git add images
        git commit -m "Hourly world map update"
        git push
