name: Process Saved Worlds
on:
  push:
    branches:
      - main

jobs:
  process-saved-worlds:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-dev python3-setuptools libjpeg-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev
          python3 -m pip install --upgrade flyingsnake
          
      - name: Run flyingsnake
        run: |
          count=0
          ignore=(33 46 60 73 94 99 110 130 140 157)
          for file in "worlds"/*; do
            if [ -f "$file" ]; then
              file_name=$(basename "$file")
              parts=(${file_name//[_]/ })
              date_part=${parts[1]}
              time_part=${parts[2]}
              new_name="images/${date_part:5}-${date_part:0:4}-${time_part:0:2}:${time_part:3:2}.png"
              echo -e "count: $count\nfilename: $file_name"
              if [[ " ${ignore[*]} " == *" $count "* ]]; then
                echo "File is in ignore list, skipping..."
                count=$((count+1))
                continue
              fi
              flyingsnake --no-wires "worlds/$file_name" images/temp.png
              mv images/temp.png $new_name
              count=$((count+1))
            fi
          done

      - name: Commit and push
        run: |
          git config user.name "InfinityNichto"
          git config user.email "u5170201@gmail.com"
          git add .
          git commit -m "Add images from old archive"    
          git pull origin main
          git push
